# This is a basic workflow to help you get started with Actions

name: CI-DEBIAN

on:
  push:
    tags:
      - 'v*.*.*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    
      # Build .deb package
      - name: build-deb-action
        uses: jiro4989/build-deb-action@v2
        with:
          package: debian-mate-artwork
          package_root: ./
          maintainer: VentGrey
          version: ${{ github.ref }}
          arch: 'all'
          depends: 'fonts-ubuntu, fonts-ubuntu-console, lightdm'
          desc: 'Debian MATE themes and artwork. This package contains Debian MATE themes and artwork.'
          
          
          
          
        
